# Generated by Django 4.2.1 on 2023-07-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
